/*
 *
 * SDHCALDetectorModule.h header template automatically generated by a class generator
 * Creation date : mer. janv. 21 2015
 *
 * This file is part of DQMSDHCAL libraries.
 * 
 * DQMSDHCAL is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQMSDHCAL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQMSDHCAL.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete, Victor Buridon
 * @copyright CNRS , IPNL
 */


#ifndef SDHCALDETECTORMODULE_H
#define SDHCALDETECTORMODULE_H

#include "lcdqm/DQMModule.h"

/** SDHCALDetectorModule class
 */ 
class SDHCALDetectorModule : public lcdqm::DQMModule
{
public:

 SDHCALDetectorModule();
 ~SDHCALDetectorModule();

 // from DQMModule interface
 lcdqm::StatusCode init();
 lcdqm::StatusCode readSettings(const lcdqm::TiXmlHandle &xmlHandle);
 lcdqm::StatusCode end();
 lcdqm::StatusCode processEvent(EVENT::LCEvent *pLCEvent);
 lcdqm::StatusCode startOfCycle();
 lcdqm::StatusCode endOfCycle();
 lcdqm::StatusCode startOfRun(EVENT::LCRunHeader *pRunHeader);
 lcdqm::StatusCode endOfRun(EVENT::LCRunHeader *pRunHeader);
 lcdqm::StatusCode reset();
 const std::string &getDetectorName() const;
 const lcdqm::DQMVersion &getVersion() const;

protected:

 std::string                  m_detectorName;
 lcdqm::DQMVersion            m_version;

 lcdqm::DQMMonitorElement      *m_pNHitPlot;
 lcdqm::DQMMonitorElement      *m_pNHit1Plot;
 lcdqm::DQMMonitorElement      *m_pNHit2Plot;
 lcdqm::DQMMonitorElement      *m_pNHit3Plot;
 lcdqm::DQMMonitorElement      *m_pTransverseShowerProfile;
 lcdqm::DQMMonitorElement      *m_pLongitudinalShowerProfile;

 unsigned int                 m_sleepTime;
}; 


#endif  //  SDHCALDETECTORMODULE_H
