/// \file Trivent.h
/*
*
* Trivent.h header template automatically generated by a class generator
* Creation date : lun. ao�t 3 2015
*
* This file is part of DQMSDHCAL libraries.
*
* DQMSDHCAL is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* based upon these libraries are permitted. Any copy of these libraries
* must include this copyright notice.
*
* DQMSDHCAL is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with DQMSDHCAL.  If not, see <http://www.gnu.org/licenses/>.
*
* @author Yacine Haddad, Arnaud Steen, Remi Ete, Antoine Pingault
* @copyright CNRS , IPNL, UGent
*/


#ifndef TRIVENT_H
#define TRIVENT_H
#define  HISTOGRAM_PARSER true


#include "dqm4hep/core/DQM4HEP.h"

namespace EVENT { class LCEvent; }

namespace dqm_sdhcal
{

/** Trivent class
*/
class Trivent
{
public:
    /** Constructor
       */
    Trivent();

    /** Destructor
       */
    ~Trivent();

    /** Process Trivent on the lcio event.
       *  Create a CalorimeterHit collection from a RawCalorimeterHit Collection from StreamOut
       */
    dqm4hep::StatusCode processEvent(EVENT::LCEvent *pLCEvent);

    void init();

    void    processEvent( LCEvent * evtP );
    void    ClearVector();
    void    fillTree();
    void    processRunHeader( LCRunHeader * runH);// added by me
    void    XMLReader(std::string xmlfile);
    void    readDifGeomFile(std::string geomfile);
    void    printDifGeom();

    uint    getCellDifId(int cellId);
    uint    getCellAsicId(int cellId);
    uint    getCellChanId(int cellId);

    void    getMaxTime();
    std::vector<int> getTimeSpectrum();
    uint*   getPadIndex(uint difId, uint asicId, uint chanId);
    void    eventBuilder(LCCollection* colEvent,int timePeak, int previousTimePeak);
    bool    peakOrNot(std::vector<int> timeSpectrum, int iTime ,int threshold);
    void    end();


    void setInputCollectionName(const std::string &inputCollectionName);

    void setOutputCollectionName(const std::string &outputCollectionName);

    void setOutputNoiseFileName(const std::string &noiseFileName);

    //  GeometryXMLFile (Default = setup_geometry.xml)
    void setGeometryXMLFile(const std::string &geomXMLFile);

    //  Cut in number of layer (Default = 10)
    void setLayerCut(const int &layerCut);

    //  Noise Cut in time spectrum (Default = 10)
    void setNoiseCut(const int &noiseCut);

    //  TimeWindow in TimeBin (Default = 2)
    void setTimeWindow(const int &timeWindow);


    // LayerGap dimension in cm (Default = .9)
    void setLayerGap(const double &layerGap);

    // Cut on number of hit max (Electronic Noise)  (Default = 100000)
    void setElecNoiseCut(const int &elecNoiseCut);

    // Cut on time from previous event in TimeBin (Default = 0)
    void setTime2PreviousEventCut(const int &time2PreviousEventCut);

    // Activate/Deativate GainCorrectionMode (Default = False)
    void setGainCorrectionMode(const bool &gainCorrectionMode);

    // Cerenkov window for event recontstruction (Default = 20)
    void setCerenkovWindow(const int &cerenkovWindow);

    // Cerenkov signal Lenght, in TimeBin (Default = 1)
    void setCerenkovLength(const int &cerenkovLength);

    // Cerenkov DifId (Default = 3)
    void setCerenkovDifId(const int &cerenkovDifId);

private:
    // xml test
    std::map<std::string,std::string> m_parameters;

    std::vector<EVENT::RawCalorimeterHit*> m_triggerRawHit;
    std::vector<EVENT::RawCalorimeterHit*> m_cerenkovHits;
    std::vector<EVENT::LCEvent*> evts; // Vector of evts reconstructed in the Trigger

    std::string _logRootName;
    std::string _mappingFile;
    std::ostream *_output;
    std::vector<std::string> _hcalCollections;
    int _overwrite;

    std::string m_inputCollectionName;
    std::string m_outputCollectionName;
    std::string m_noiseFileName;
    std::string m_geomXMLFile;

    int m_layerCut;
    int m_noiseCut;
    int m_timeWindow;
    double m_layerGap;
    int m_elecNoiseCut;
    int m_time2PreviousEventCut;
    bool m_gainCorrectionMode;
    int m_cerenkovWindow;
    int m_cerenkovLength;
    int m_cerenkovDifId;

    float m_beamEnergy;
    int m_trigCount;
    int m_maxTime;
    int m_evtNbr;
    int m_previousEvtNbr;
    int m_rejectedEvt;
    int m_selectedEvt;
    uint m_index[3];
    uintVec _zCut;
    LCWriter* _lcWriter;
    int m_bcid1;
    int m_bcid2;
    bool m_cerenkovFlag[3];
    int m_cerenkovCount[3];
    int m_cerenkovCountTotal[3];



    // ------------- ROOT
    TH1F *noise_dist;
    TH1F *gain_chan;
    TH1F *mean_hit_dif;
    TH1F *time_hit_dif;

    TFile *_file;
    TTree *_tree;
    TClonesArray *_hitArray;
    TClonesArray *_rootArray;// added by me
    unsigned int _triggerNbr;
    unsigned int _runNbr;
    unsigned int _eventType;
    Int_t _evtId;

    std::vector<int> x;
    std::vector<int> y;
    std::vector<int> z;
    std::vector<int> fThr;
    std::vector<int> fDifId;
    std::vector<int> fNevt;
    std::vector<int> fEvtReconstructed;
    std::vector<int> fPrevTime;
    std::vector<int> fTime;
    std::vector<int> fTimePeak;
    std::vector<int> fPrevTimePeak;
    std::vector<int> fDeltaTimePeak;
    std::vector<int> fTriggerNr;
    std::vector<int> fNhit;
    std::vector<int> fCerenkovTag1;
    std::vector<int> fCerenkovTag2;
    std::vector<int> fCerenkovTag3;
    std::vector<int> fCerenkovCount1;
    std::vector<int> fCerenkovCount2;
    std::vector<int> fCerenkovCount3;
    std::vector<int> fCerenkovCountDecember;
    std::vector<int> fPion;
    std::vector<int> fElectron;
    std::vector<int> fMuon;


    unsigned int _eventNbr;
    Int_t _nHit;
    Int_t _elecNoiseCut;

    std::map<int, LayerID  > _mapping;
    std::map<int, double  > _chamberPos;//camber , pos



    std::string normal  ;
    std::string red     ;
    std::string green   ;
    std::string yellow  ;
    std::string blue    ;
    std::string magenta ;
    std::string white   ;

};

}

#endif  //  Trivent_H
