  /// \file Decoder.h
/*
 *
 * Decoder.h header template automatically generated by a class generator
 * Creation date : mar. mai 5 2015
 *
 * This file is part of DQMSDHCAL libraries.
 * 
 * DQMSDHCAL is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQMSDHCAL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQMSDHCAL.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef DECODER_H
#define DECODER_H

#include <stdint.h>

namespace dqm_sdhcal
{

/** 
 * @brief Decoder class
 */ 
class Decoder 
{
public:
	static uint32_t getBufferDIF(unsigned char* cb,uint32_t idx=0);

	static uint32_t getBufferDTC(unsigned char* cb,uint32_t idx=0);

	static uint32_t getBufferGTC(unsigned char* cb,uint32_t idx=0);

//	static unsigned long long getBufferABCID(unsigned char* cb,uint32_t idx=0);
//
//	static uint32_t getBufferDIFTemp(unsigned char* cb,uint32_t idx=0);
//
//	static unsigned char*  packDIFData(unsigned char* cbuf,uint32_t size,uint32_t gtc,uint32_t dtc,uint32_t id);
}; 

} 

#endif  //  DECODER_H
